In [1]:
import numpy as np
from sentence_transformers import SentenceTransformer

/Users/cfe/Dev/talk-to-django/venv/lib/python3.11/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [2]:
model = SentenceTransformer("all-MiniLM-L6-v2")

In [6]:
split_docs = sorted(["The dog jumped over the cat"][0].split(' '))
split_docs

['The', 'cat', 'dog', 'jumped', 'over', 'the']

In [7]:
docs = ["The dog jumped over the cat"]
docs

['The dog jumped over the cat']

In [9]:
embeddings = model.encode(docs)

In [11]:
docs2 = ["The cat jumped over the dog"]

In [12]:
split_docs2 = sorted(docs2[0].split(' '))
split_docs2

['The', 'cat', 'dog', 'jumped', 'over', 'the']

In [13]:
embeddings2 = model.encode(docs2)

In [21]:
model.similarity(embeddings,embeddings)

tensor([[1.0000]])

In [16]:
model.similarity(embeddings,embeddings2)

tensor([[0.9895]])

In [19]:
embeddings3 = model.encode(["The dog is hot from jumping"])

In [20]:
model.similarity(embeddings,embeddings3)

tensor([[0.4310]])

In [22]:
embeddings4 = model.encode(["The weather is hot"])
model.similarity(embeddings,embeddings4)

tensor([[-0.0660]])

In [23]:
embeddings2

array([[ 4.72092927e-02,  3.36049646e-02,  6.90095648e-02,
         6.85966387e-02, -1.26861297e-02, -6.25286764e-03,
        -3.72543260e-02,  1.55753568e-02,  2.41127852e-02,
         2.21969979e-03,  7.17992783e-02,  2.92151421e-02,
         5.03158709e-03, -6.37696981e-02,  4.89643309e-03,
         1.07082445e-03, -1.23178743e-01,  9.51716863e-03,
         5.84049039e-02, -1.34706022e-02, -2.93736849e-02,
        -4.55944873e-02, -1.06726373e-02, -4.11552712e-02,
        -3.63231786e-02,  3.73865589e-02, -8.08678716e-02,
        -6.92620501e-02,  1.39805004e-02, -1.62780806e-02,
        -2.12399829e-02, -8.98967776e-03, -3.35779712e-02,
         5.97752631e-02, -6.10135272e-02, -7.63887540e-02,
         6.19942881e-02,  3.30313668e-03,  3.82678136e-02,
         1.23094983e-01, -3.98203246e-02,  7.74865597e-03,
        -1.22557981e-02, -2.10484420e-03, -3.81270237e-02,
         6.25126734e-02, -1.30796088e-02, -6.36047423e-02,
         3.17579880e-02,  5.67504615e-02, -1.24571053e-0